//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entry()
        {
            this.Exit = new HashSet<Exit>();
        }
    
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int roomNumber { get; set; }
        public int bedNumber { get; set; }
        public string diagnostic { get; set; }
        public string observation { get; set; }
        public bool deleted { get; set; }
        public long medicId { get; set; }
        public long patientId { get; set; }
    
        public virtual Medic Medic { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exit> Exit { get; set; }
    }
}
