//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exit
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public string treatment { get; set; }
        public decimal cost { get; set; }
        public bool deleted { get; set; }
        public long medicId { get; set; }
        public long entryId { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Medic Medic { get; set; }
    }
}
